[project]
name = "racine"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pandas>=2.2.3",
    "retrying>=1.3.4",
    "schedule>=1.2.2",
    "xlsxwriter>=3.2.0",
]
